apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: classification-banner
spec:
  text: "INTERN - Nur fuer autorisierten Zugriff"
  location: BannerTop
  color: "#ffffff"
  backgroundColor: "#cc0000"
