apiVersion: quota.openshift.io/v1
kind: ClusterResourceQuota
metadata:
  name: cluster-wide-quota
spec:
  quota:
    hard:
      requests.cpu: "40"
      requests.memory: 80Gi
      limits.cpu: "80"
      limits.memory: 160Gi
      pods: "200"
      persistentvolumeclaims: "50"
  selector:
    labels:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - default
            - openshift
            - kube-system
            - openshift-compliance
            - openshift-gitops
            - openshift-gitops-operator
            - openshift-external-secrets-operator
            - external-secrets
            - vault
            - cert-manager-operator
            - openshift-marketplace