apiVersion: config.openshift.io/v1
kind: Image
metadata:
  name: cluster
spec:
  registrySources:
    allowedRegistries:
      - registry.redhat.io
      - registry.access.redhat.com
      - registry.connect.redhat.com
      - quay.io
      - docker.io
      - image-registry.openshift-image-registry.svc:5000
  allowedRegistriesForImport:
    - domainName: registry.redhat.io
      insecure: false
    - domainName: registry.access.redhat.com
      insecure: false
    - domainName: registry.connect.redhat.com
      insecure: false
    - domainName: quay.io
      insecure: false
    - domainName: docker.io
      insecure: false
    - domainName: image-registry.openshift-image-registry.svc:5000
      insecure: false
