apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: rhcos4-moderate-tailored
  namespace: openshift-compliance
spec:
  description: RHCOS4 Moderate - CRC angepasst
  title: RHCOS4 Moderate Tailored
  extends: rhcos4-moderate
  disableRules:
    # FIPS nicht möglich in CRC
    - name: rhcos4-moderate-enable-fips-mode
      rationale: "FIPS wird von CRC nicht unterstützt"
    # USB nicht relevant in CRC
    - name: rhcos4-moderate-package-usbguard-installed
      rationale: "USB nicht relevant in CRC"
    - name: rhcos4-moderate-service-usbguard-enabled
      rationale: "USB nicht relevant in CRC"
    - name: rhcos4-moderate-usbguard-allow-hid-and-hub
      rationale: "USB nicht relevant in CRC"
    - name: rhcos4-moderate-coreos-nousb-kernel-argument
      rationale: "USB nicht relevant in CRC"