apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace-policies
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - namespace: example-app
  template:
    metadata:
      name: "namespace-policies-{{namespace}}"
    spec:
      project: platform
      source:
        repoURL: https://github.com/chriwo42-lang/ocp-platform.git
        targetRevision: main
        path: workloads/namespace-template
        helm:
          values: |
            namespace: {{namespace}}
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true