apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  source:
    repoURL: https://github.com/chriwo42-lang/ocp-platform.git
    targetRevision: main
    path: cluster-config
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}