apiVersion: argoproj.io/v1beta1
kind: Application
metadata:
  name: operators
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/chriwo42-lang/ocp-platform.git
    targetRevision: main
    path: operators
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
