apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
spec:
  description: Workloads - Applikationen
  sourceRepos:
    - https://github.com/chriwo42-lang/ocp-workloads.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: workloads-admin
      policies:
        - p, proj:workloads:workloads-admin, applications, *, workloads/*, allow
      groups:
        - cluster-admins